### Pit stops in one row

In [17]:
import pandas as pd

In [18]:
pit_stops_df = pd.read_csv("data/pit_stops.csv")

In [19]:


# Replace this with your actual data import method

# Create a DataFrame for pit stops with 'stop' equal to 2
pit_stop_2_df = pit_stops_df[pit_stops_df['stop'] == 2]

# Rename columns in the pit_stop_2_df to avoid conflicts when merging
pit_stop_2_df = pit_stop_2_df.rename(columns={
    'lap': 'pit_stop_2_lap',
    'time': 'pit_stop_2_time',
    'duration': 'pit_stop_2_duration',
    'milliseconds': 'pit_stop_2_milliseconds'
}) 

# Merge the pit_stop_2_df with the original DataFrame using raceId and driverId
merged_df = pit_stops_df.merge(pit_stop_2_df[['raceId', 'driverId', 'pit_stop_2_lap', 'pit_stop_2_time', 'pit_stop_2_duration', 'pit_stop_2_milliseconds']], on=['raceId', 'driverId'], how='left')

# Fill NaN values with appropriate values (0 in this case)
merged_df = merged_df.fillna(0)

# Drop the duplicate rows with the same raceId and driverId
merged_df = merged_df.drop_duplicates(subset=['raceId', 'driverId'])

# Reset index if needed
merged_df = merged_df.reset_index(drop=True)

# Print the resulting DataFrame
print(merged_df)

      raceId  driverId  stop  lap      time duration  milliseconds
0        841       153     1    1  17:05:23   26.898         26898  \
1        841        30     1    1  17:05:52   25.021         25021
2        841        17     1   11  17:20:48   23.426         23426
3        841         4     1   12  17:22:34   23.251         23251
4        841        13     1   13  17:24:10   23.842         23842
...      ...       ...   ...  ...       ...      ...           ...
4696    1096       830     1   20  17:33:31   22.735         22735
4697    1096       844     1   21  17:35:10   22.210         22210
4698    1096        20     1   25  17:41:51   23.186         23186
4699    1096       825     1   28  17:46:53   22.387         22387
4700    1096       822     1   30  17:49:54   22.573         22573

      pit_stop_2_lap pit_stop_2_time pit_stop_2_duration
0               17.0        17:31:06              24.463  \
1               17.0        17:32:08              23.988
2               26.0        17:44:29              22.520
3               27.0        17:46:04              24.733
4               31.0        17:52:28              24.500
...              ...             ...                 ...
4696             0.0               0                   0
4697             0.0               0                   0
4698             0.0               0                   0
4699             0.0               0                   0
4700             0.0               0                   0

      pit_stop_2_milliseconds
0                     24463.0
1                     23988.0
2                     22520.0
3                     24733.0
4                     24500.0
...                       ...
4696                      0.0
4697                      0.0
4698                      0.0
4699                      0.0
4700                      0.0

[4701 rows x 11 columns]

In [20]:
# Define a list of stop values to consider
stop_values = [1, 2, 3, 4, 5, 6]

# Create an empty DataFrame to store the merged data
merged_df = pit_stops_df.copy()

# Iterate through stop values and merge the corresponding DataFrames
for stop_value in stop_values:
    # Filter the DataFrame for the current stop value
    pit_stop_df = pit_stops_df[pit_stops_df['stop'] == stop_value]
    
    # Rename columns to avoid conflicts when merging
    pit_stop_df = pit_stop_df.rename(columns={
        'lap': f'pit_stop_{stop_value}_lap',
        'time': f'pit_stop_{stop_value}_time',
        'duration': f'pit_stop_{stop_value}_duration',
        'milliseconds': f'pit_stop_{stop_value}_milliseconds'
    })

    # Merge the current pit stop data with the merged DataFrame
    merged_df = merged_df.merge(pit_stop_df[['raceId', 'driverId', f'pit_stop_{stop_value}_lap', f'pit_stop_{stop_value}_time', f'pit_stop_{stop_value}_duration', f'pit_stop_{stop_value}_milliseconds']], on=['raceId', 'driverId'], how='left')

# Fill NaN values with appropriate values (0 in this case)
merged_df = merged_df.fillna(0)

# Drop the duplicate rows with the same raceId and driverId
merged_df = merged_df.drop_duplicates(subset=['raceId', 'driverId'])

# Reset index if needed
merged_df = merged_df.reset_index(drop=True)

# Print the resulting DataFrame
print(merged_df)

      raceId  driverId  stop  lap      time duration  milliseconds
0        841       153     1    1  17:05:23   26.898         26898  \
1        841        30     1    1  17:05:52   25.021         25021
2        841        17     1   11  17:20:48   23.426         23426
3        841         4     1   12  17:22:34   23.251         23251
4        841        13     1   13  17:24:10   23.842         23842
...      ...       ...   ...  ...       ...      ...           ...
4696    1096       830     1   20  17:33:31   22.735         22735
4697    1096       844     1   21  17:35:10   22.210         22210
4698    1096        20     1   25  17:41:51   23.186         23186
4699    1096       825     1   28  17:46:53   22.387         22387
4700    1096       822     1   30  17:49:54   22.573         22573

      pit_stop_1_lap pit_stop_1_time pit_stop_1_duration  ...
0                1.0        17:05:23              26.898  ...  \
1                1.0        17:05:52              25.021  ...
2               11.0        17:20:48              23.426  ...
3               12.0        17:22:34              23.251  ...
4               13.0        17:24:10              23.842  ...
...              ...             ...                 ...  ...
4696            20.0        17:33:31              22.735  ...
4697            21.0        17:35:10              22.210  ...
4698            25.0        17:41:51              23.186  ...
4699            28.0        17:46:53              22.387  ...
4700            30.0        17:49:54              22.573  ...

      pit_stop_4_duration  pit_stop_4_milliseconds pit_stop_5_lap
0                       0                      0.0            0.0  \
1                       0                      0.0            0.0
2                       0                      0.0            0.0
3                       0                      0.0            0.0
4                       0                      0.0            0.0
...                   ...                      ...            ...
4696                    0                      0.0            0.0
4697                    0                      0.0            0.0
4698                    0                      0.0            0.0
4699                    0                      0.0            0.0
4700                    0                      0.0            0.0

     pit_stop_5_time  pit_stop_5_duration  pit_stop_5_milliseconds
0                  0                    0                      0.0  \
1                  0                    0                      0.0
2                  0                    0                      0.0
3                  0                    0                      0.0
4                  0                    0                      0.0
...              ...                  ...                      ...
4696               0                    0                      0.0
4697               0                    0                      0.0
4698               0                    0                      0.0
4699               0                    0                      0.0
4700               0                    0                      0.0

     pit_stop_6_lap pit_stop_6_time  pit_stop_6_duration
0               0.0               0                    0  \
1               0.0               0                    0
2               0.0               0                    0
3               0.0               0                    0
4               0.0               0                    0
...             ...             ...                  ...
4696            0.0               0                    0
4697            0.0               0                    0
4698            0.0               0                    0
4699            0.0               0                    0
4700            0.0               0                    0

      pit_stop_6_milliseconds
0                         0.0
1                         0.0
2                         0.0
3                         0.0
4                         0.0
...                       ...
4696                      0.0
4697                      0.0
4698                      0.0
4699                      0.0
4700                      0.0

[4701 rows x 31 columns]

In [21]:
merged_df.head()

,raceId,driverId,stop,lap,time,duration,milliseconds,pit_stop_1_lap,pit_stop_1_time,pit_stop_1_duration,...,pit_stop_4_duration,pit_stop_4_milliseconds,pit_stop_5_lap,pit_stop_5_time,pit_stop_5_duration,pit_stop_5_milliseconds,pit_stop_6_lap,pit_stop_6_time,pit_stop_6_duration,pit_stop_6_milliseconds
0,841,153,1,1,17:05:23,26.898,26898,1.0,17:05:23,26.898,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0
1,841,30,1,1,17:05:52,25.021,25021,1.0,17:05:52,25.021,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0
2,841,17,1,11,17:20:48,23.426,23426,11.0,17:20:48,23.426,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0
3,841,4,1,12,17:22:34,23.251,23251,12.0,17:22:34,23.251,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0
4,841,13,1,13,17:24:10,23.842,23842,13.0,17:24:10,23.842,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0

In [22]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4701 entries, 0 to 4700
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   raceId                   4701 non-null   int64
 1   driverId                 4701 non-null   int64
 2   stop                     4701 non-null   int64
 3   lap                      4701 non-null   int64
 4   time                     4701 non-null   object
 5   duration                 4701 non-null   object
 6   milliseconds             4701 non-null   int64
 7   pit_stop_1_lap           4701 non-null   float64
 8   pit_stop_1_time          4701 non-null   object
 9   pit_stop_1_duration      4701 non-null   object
 10  pit_stop_1_milliseconds  4701 non-null   float64
 11  pit_stop_2_lap           4701 non-null   float64
 12  pit_stop_2_time          4701 non-null   object
 13  pit_stop_2_duration      4701 non-null   object
 14  pit_stop_2_milliseconds  4701 non-null   float64
 15  pit_stop_3_lap           4701 non-null   float64
 16  pit_stop_3_time          4701 non-null   object
 17  pit_stop_3_duration      4701 non-null   object
 18  pit_stop_3_milliseconds  4701 non-null   float64
 19  pit_stop_4_lap           4701 non-null   float64
 20  pit_stop_4_time          4701 non-null   object
 21  pit_stop_4_duration      4701 non-null   object
 22  pit_stop_4_milliseconds  4701 non-null   float64
 23  pit_stop_5_lap           4701 non-null   float64
 24  pit_stop_5_time          4701 non-null   object
 25  pit_stop_5_duration      4701 non-null   object
 26  pit_stop_5_milliseconds  4701 non-null   float64
 27  pit_stop_6_lap           4701 non-null   float64
 28  pit_stop_6_time          4701 non-null   object
 29  pit_stop_6_duration      4701 non-null   object
 30  pit_stop_6_milliseconds  4701 non-null   float64
dtypes: float64(12), int64(5), object(14)
memory usage: 1.1+ MB